INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_INATELMODEM5G inatelModem5g)

FIND_PATH(
    INATELMODEM5G_INCLUDE_DIRS
    NAMES inatelModem5g/api.h
    HINTS $ENV{INATELMODEM5G_DIR}/include
        ${PC_INATELMODEM5G_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    INATELMODEM5G_LIBRARIES
    NAMES gnuradio-inatelModem5g
    HINTS $ENV{INATELMODEM5G_DIR}/lib
        ${PC_INATELMODEM5G_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(INATELMODEM5G DEFAULT_MSG INATELMODEM5G_LIBRARIES INATELMODEM5G_INCLUDE_DIRS)
MARK_AS_ADVANCED(INATELMODEM5G_LIBRARIES INATELMODEM5G_INCLUDE_DIRS)

